/**
 * 国名リスト (国旗表示用)
 * World Boccia Members + ASEAN Countries
 */
export const COUNTRIES = [
  { id: 'none', ja: 'なし', en: 'None', code: 'xx' },
  { id: 'argentina', ja: 'アルゼンチン', en: 'Argentina', code: 'ar' },
  { id: 'armenia', ja: 'アルメニア', en: 'Armenia', code: 'am' },
  { id: 'aruba', ja: 'アルバ', en: 'Aruba', code: 'aw' },
  { id: 'australia', ja: 'オーストラリア', en: 'Australia', code: 'au' },
  { id: 'austria', ja: 'オーストリア', en: 'Austria', code: 'at' },
  { id: 'azerbaijan', ja: 'アゼルバイジャン', en: 'Azerbaijan', code: 'az' },
  { id: 'bahrain', ja: 'バーレーン', en: 'Bahrain', code: 'bh' },
  { id: 'belgium', ja: 'ベルギー', en: 'Belgium', code: 'be' },
  { id: 'bermuda', ja: 'バミューダ', en: 'Bermuda', code: 'bm' },
  { id: 'brazil', ja: 'ブラジル', en: 'Brazil', code: 'br' },
  { id: 'brunei', ja: 'ブルネイ', en: 'Brunei Darussalam', code: 'bn' },
  { id: 'cambodia', ja: 'カンボジア', en: 'Cambodia', code: 'kh' },
  { id: 'cameroon', ja: 'カメルーン', en: 'Cameroon', code: 'cm' },
  { id: 'canada', ja: 'カナダ', en: 'Canada', code: 'ca' },
  { id: 'chile', ja: 'チリ', en: 'Chile', code: 'cl' },
  { id: 'china', ja: '中国', en: 'China', code: 'cn' },
  { id: 'chinese_taipei', ja: '台湾', en: 'Chinese Taipei', code: 'tw' },
  { id: 'colombia', ja: 'コロンビア', en: 'Colombia', code: 'co' },
  { id: 'costa_rica', ja: 'コスタリカ', en: 'Costa Rica', code: 'cr' },
  { id: 'croatia', ja: 'クロアチア', en: 'Croatia', code: 'hr' },
  { id: 'cyprus', ja: 'キプロス', en: 'Cyprus', code: 'cy' },
  { id: 'czech_republic', ja: 'チェコ', en: 'Czech Republic', code: 'cz' },
  { id: 'denmark', ja: 'デンマーク', en: 'Denmark', code: 'dk' },
  { id: 'ecuador', ja: 'エクアドル', en: 'Ecuador', code: 'ec' },
  { id: 'egypt', ja: 'エジプト', en: 'Egypt', code: 'eg' },
  { id: 'el_salvador', ja: 'エルサルバドル', en: 'El Salvador', code: 'sv' },
  { id: 'england', ja: 'イングランド', en: 'England', code: 'gb-eng' },
  { id: 'faroe_islands', ja: 'フェロー諸島', en: 'Faroe Islands', code: 'fo' },
  { id: 'finland', ja: 'フィンランド', en: 'Finland', code: 'fi' },
  { id: 'france', ja: 'フランス', en: 'France', code: 'fr' },
  { id: 'georgia', ja: 'ジョージア', en: 'Georgia', code: 'ge' },
  { id: 'germany', ja: 'ドイツ', en: 'Germany', code: 'de' },
  { id: 'ghana', ja: 'ガーナ', en: 'Ghana', code: 'gh' },
  { id: 'great_britain', ja: 'イギリス', en: 'Great Britain', code: 'gb' },
  { id: 'greece', ja: 'ギリシャ', en: 'Greece', code: 'gr' },
  { id: 'guatemala', ja: 'グアテマラ', en: 'Guatemala', code: 'gt' },
  { id: 'hong_kong', ja: '香港', en: 'Hong Kong, China', code: 'hk' },
  { id: 'hungary', ja: 'ハンガリー', en: 'Hungary', code: 'hu' },
  { id: 'iceland', ja: 'アイスランド', en: 'Iceland', code: 'is' },
  { id: 'india', ja: 'インド', en: 'India', code: 'in' },
  { id: 'indonesia', ja: 'インドネシア', en: 'Indonesia', code: 'id' },
  { id: 'iran', ja: 'イラン', en: 'Iran', code: 'ir' },
  { id: 'iraq', ja: 'イラク', en: 'Iraq', code: 'iq' },
  { id: 'ireland', ja: 'アイルランド', en: 'Ireland', code: 'ie' },
  { id: 'israel', ja: 'イスラエル', en: 'Israel', code: 'il' },
  { id: 'italy', ja: 'イタリア', en: 'Italy', code: 'it' },
  { id: 'jamaica', ja: 'ジャマイカ', en: 'Jamaica', code: 'jm' },
  { id: 'japan', ja: '日本', en: 'Japan', code: 'jp' },
  { id: 'kazakhstan', ja: 'カザフスタン', en: 'Kazakhstan', code: 'kz' },
  { id: 'kenya', ja: 'ケニア', en: 'Kenya', code: 'ke' },
  { id: 'korea', ja: '韓国', en: 'Korea', code: 'kr' },
  { id: 'kuwait', ja: 'クウェート', en: 'Kuwait', code: 'kw' },
  { id: 'laos', ja: 'ラオス', en: 'Lao PDR', code: 'la' },
  { id: 'macau', ja: 'マカオ', en: 'Macau, China', code: 'mo' },
  { id: 'malaysia', ja: 'マレーシア', en: 'Malaysia', code: 'my' },
  { id: 'mexico', ja: 'メキシコ', en: 'Mexico', code: 'mx' },
  { id: 'mongolia', ja: 'モンゴル', en: 'Mongolia', code: 'mn' },
  { id: 'morocco', ja: 'モロッコ', en: 'Morocco', code: 'ma' },
  { id: 'myanmar', ja: 'ミャンマー', en: 'Myanmar', code: 'mm' },
  { id: 'namibia', ja: 'ナミビア', en: 'Namibia', code: 'na' },
  { id: 'netherlands', ja: 'オランダ', en: 'Netherlands', code: 'nl' },
  { id: 'new_zealand', ja: 'ニュージーランド', en: 'New Zealand', code: 'nz' },
  { id: 'norway', ja: 'ノルウェー', en: 'Norway', code: 'no' },
  { id: 'panama', ja: 'パナマ', en: 'Panama', code: 'pa' },
  { id: 'peru', ja: 'ペルー', en: 'Peru', code: 'pe' },
  { id: 'philippines', ja: 'フィリピン', en: 'Philippines', code: 'ph' },
  { id: 'poland', ja: 'ポーランド', en: 'Poland', code: 'pl' },
  { id: 'portugal', ja: 'ポルトガル', en: 'Portugal', code: 'pt' },
  { id: 'russia', ja: 'ロシア', en: 'Russia', code: 'ru' },
  { id: 'rwanda', ja: 'ルワンダ', en: 'Rwanda', code: 'rw' },
  { id: 'saudi_arabia', ja: 'サウジアラビア', en: 'Saudi Arabia', code: 'sa' },
  { id: 'singapore', ja: 'シンガポール', en: 'Singapore', code: 'sg' },
  { id: 'slovakia', ja: 'スロバキア', en: 'Slovak Republic', code: 'sk' },
  { id: 'slovenia', ja: 'スロベニア', en: 'Slovenia', code: 'si' },
  { id: 'south_africa', ja: '南アフリカ', en: 'South Africa', code: 'za' },
  { id: 'spain', ja: 'スペイン', en: 'Spain', code: 'es' },
  { id: 'swedish', ja: 'スウェーデン', en: 'Sweden', code: 'se' },
  { id: 'thailand', ja: 'タイ', en: 'Thailand', code: 'th' },
  { id: 'tunisia', ja: 'チュニジア', en: 'Tunisia', code: 'tn' },
  { id: 'turkiye', ja: 'トルコ', en: 'Turkiye', code: 'tr' },
  { id: 'ukraine', ja: 'ウクライナ', en: 'Ukraine', code: 'ua' },
  { id: 'united_arab_emirates', ja: 'アラブ首長国連邦', en: 'United Arab Emirates', code: 'ae' },
  { id: 'united_states', ja: 'アメリカ', en: 'United States', code: 'us' },
  { id: 'uruguay', ja: 'ウルグアイ', en: 'Uruguay', code: 'uy' },
  { id: 'uzbekistan', ja: 'ウズベキスタン', en: 'Uzbekistan', code: 'uz' },
  { id: 'venezuela', ja: 'ベネズエラ', en: 'Venezuela', code: 've' },
  { id: 'vietnam', ja: 'ベトナム', en: 'Vietnam', code: 'vn' },
  { id: 'timor_leste', ja: '東ティモール', en: 'Timor-Leste', code: 'tl' }
];
